module.exports = ["Woodland Elementary", "Maple Grove Middle School", "Pinecrest High School",
                  "Sunnyvale Elementary", "Oakridge Middle School", "Riverdale High School",
                   "Meadowbrook Elementary", "Willow Creek Middle School", "Lakeside High School", 
                   "Greenfield Elementary", "Cedar Ridge Middle School", "Summit High School", 
                   "Spring Valley Elementary", "Birchwood Middle School", "Mountainview High School", 
                   "Riverside Elementary", "Elmwood Middle School", "Crestwood High School", 
                   "Brookside Elementary", "Forest Hills Middle School", "Hilltop High School", 
                   "Lincoln Elementary", "Maplewood Middle School", "Valley High School", 
                   "Willowbrook Elementary", "Pineview Middle School", "Lakeshore High School", 
                   "Oakdale Elementary", "Riverbend Middle School", "Sunset High School", 
                   "Maplewood Elementary", "Sunnyside Middle School", "Westside High School", 
                   "Meadowlark Elementary", "Cedarwood Middle School", "Lakewood High School", 
                   "Hillcrest Elementary", "Parkview Middle School", "Greenwood High School", 
                   "Brookview Elementary", "Willow Grove Middle School", "Hillcrest High School", 
                   "Lakeview Elementary", "Forest Glen Middle School", "Pinecrest High School", 
                   "Elmwood Elementary", "Riverdale Middle School", "Oakridge High School", 
                   "Birchwood Elementary", "Spring Valley Middle School", "Summit High School", 
                   "Sunset Elementary", "Oakwood Middle School", "Greenfield High School", 
                   "Riverwood Elementary", "Maple Grove Middle School", "Woodland High School", 
                   "Lakeside Elementary", "Sunnyvale Middle School", "Cedar Ridge High School"];